# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy

on:
  push:
    branches: [ main, github-action-testing ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build

      - name: Archive build/ directory
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
      - run: |
          git clone https://CrispinStichart:${{ ACCESS_TOKEN }}@github.com/CrispinStichart/wordle-result-editor-website.git repo
          cd repo
          rm -rf *
          touch .nojekyll
          mv -f ../build/* .
          git add -A
          git commit -m "Automatic commit"
          git push
